inherit: ["config.yml"]
bookname: louisa-works-2023-2-print
prt: ねこのしっぽ
texdocumentclass: ["review-jlreq", "media=print,paper=a6,fontsize=8pt,serial_pagination=true,hiddenfolio=shippo,startpage=3,tate,twoside,onecolumn,openany"]